title: Carl Elgin - Professional
author: Carl Elgin
email: carl.elgin@gmail.com
description: This site will serve as my portfolio and resume

# social links
twitter_username: your-twitter-handle
github_username:  cjelgin

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

header_pages:
  - about.md
  - portfolio.md
